# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r
warnings_are_errors: true
sudo: required

bioc_packages:
    - bioDist
    - limma
    - preprocessCore

notifications:
    email:
        on_success: change
        on_failure: change